### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [lexxvir/tlv-parser#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by lexxvir** [comment]
I need to_hex/from_hex functionality just for few things.
So try to find another crate or switch to serde.

**Comment by lexxvir** [comment]
Released in version [0.1.5](https://crates.io/crates/tlv_parser/0.1.5)
